object Version {
    const val gradleVersion = "7.1.3"
    const val kotlinGradleVersion = "1.6.21"
    const val googlePlayServiceVersion = "4.3.0"
    const val hiltGradleVersion = "2.38.1"
    const val coreKtxVersion = "1.7.0"
    const val appCompatVersion = "1.1.0-alpha04"
    const val materialVersion = "1.5.0"
    const val constraintLayoutVersion = "2.1.3"
    const val legacyVersion = "1.0.0"
    const val junitVersion = "4.13.2"
    const val junitTestVersion = "1.1.3"
    const val espressoVersion = "3.4.0"
    const val firebaseAuthKtxVersion = "21.0.3"
    const val firebaseAuthUiVersion = "7.2.0"
    const val firebaseMessagingVersion = "23.0.3"
    const val firebaseDynamicLinksVersion = "21.0.1"
    const val firebaseAnalyticsVersion = "20.1.2"
    const val coroutineVersion = "1.6.2"
    const val retrofitVersion = "2.9.0"
    const val interceptorVersion = "4.9.0"
    const val navigationVersion = "2.4.2"
    const val locationVersion = "19.0.1"
    const val glideVersion = "4.13.0"
    const val hiltVersion = "2.38.1"
    const val timberVersion = "5.0.1"
    const val loggerVersion = "2.2.0"
    const val lifecycleKtxVersion = "2.4.1"
    const val fragmentKtxVersion = "1.4.1"
    const val dataStoreVersion = "1.0.0"
    const val leakCanaryVersion = "2.9.1"
    const val coilVersion = "2.0.0-rc03"
    const val serializationVersion = "1.2.2"
    const val viewPagerVersion = "1.0.0"
    const val roundImageViewVersion = "2.3.0"

}